[package]
name = "bevy_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7", features=["jpeg", "dynamic"] }
bevy_rapier3d = { version = "0.13.2", features=["debug-render"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
